# Generated by Django 5.0.3 on 2024-03-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_imagemodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='title',
        ),
    ]
