# Generated by Django 5.0.3 on 2024-03-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_remove_imagemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
